# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Entities-Numbered
version:      0.01
version_from: lib/HTML/Entities/Numbered.pm
installdirs:  site
requires:
    HTML::Entities:                1.27
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
